### ISSUE TITLE
is the operation of GCN convolution wrong in models.py

### ISSUE THREAD

**Issue by smallhaes** [KaidiXu/GCN_ADV_Train#2]
line 190 of in models.py 
`self.support_real = tf.multiply(tf.transpose(tf.multiply(self.hat_A[0],self.d_sqrt_inv)),self.d_sqrt_inv)`
the operation of convolution is H = f(AHW^(t)) with matrix multiplication
however, it is element-wise multiplication in models.py like tf.multiply().
so, is it an error or is there anything i misunderstood ?

**Comment by chenhongge** [comment]
Hi @smallhaes, thanks for your interest to our repo! I don't think it's an error, though. 
This line is not calculating AHW^(t), but just calculating D^{-1/2}\hat{A}D^{-1/2}, where D is a diagonal matrix representing A's degree. Basically, `self.d_sqrt_inv` is D^{-1/2}, but in its vector form (the vector of D^{-1/2}'s non-zero diagonal), see lines 186~188. 
Also, `tf.multiply` has its broadcast rule, so `tf.multiply(self.hat_A[0],self.d_sqrt_inv)` is basically \hat{A}D^{-1/2}. 
Then the whole line basically gives (\hat{A}D^{-1/2})^TD^{-1/2}= D^{-1/2}\hat{A}D^{-1/2} since A is symmetric. Please let us know if you have any other questions!

**Comment by smallhaes** [comment]
thanks~ 😄 
another question, does the minux sign in D^{-1/2} denotes reciprocal instead of inverse of matrix ?
if it denotes the inverse of matrix, does  `tf.math.reciprocal(self.d_sqrt)`  still make sense? as we know, `tf.math.reciprocal()` outputs the reciprocal rather than the inverse of matrix

**Comment by smallhaes** [comment]
figure the second problem out ~ D^{-1/2} denotes the inverse of matrix. and D is diagonal matrix so D^{-1/2}  also be denoted by reciprocal.

as for `self.support_real = tf.multiply(tf.transpose(tf.multiply(self.hat_A[0],self.d_sqrt_inv)),self.d_sqrt_inv)`, 
i just add two new lines below 
`self.d_sqrt_inv2 = tf.diag(self.d_sqrt_inv)`
`self.support_real2 = tf.matmul(tf.transpose(tf.matmul(self.hat_A[0],self.d_sqrt_inv2)), self.d_sqrt_inv2)`
i think self.support_real should equal self.support_real2, but they are not equal, am i wrong?

**Comment by chenhongge** [comment]
Since you already used `tf.diag` to convert the vector to diagonal matrix, I think you should always use `tf.matmul`. If you still use `tf.multiply`, it will do elementwise product.

**Comment by smallhaes** [comment]
sorry, i made a mistake in 
`self.support_real2 = tf.multiply(tf.transpose(tf.matmul(self.hat_A[0],self.d_sqrt_inv2)), self.d_sqrt_inv2)`
it should be
`self.support_real2 = tf.matmul(tf.transpose(tf.matmul(self.hat_A[0],self.d_sqrt_inv2)), self.d_sqrt_inv2)`
self.support_real is equal to self.support_real2

Thanks a lot for your explanation! 👍
